// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA0OfgYQ_EhWu3AluzFydosqwAslCXngc',
    appId: '1:396867608722:web:f670260d0dc9acfe7b064b',
    messagingSenderId: '396867608722',
    projectId: 'madic-834c8',
    authDomain: 'madic-834c8.firebaseapp.com',
    storageBucket: 'madic-834c8.firebasestorage.app',
    measurementId: 'G-Y7JCRL2GX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPr7vQBEL-G_NAaGbdG8L9hmWafqOpOU',
    appId: '1:396867608722:android:de6a4e820b31e20c7b064b',
    messagingSenderId: '396867608722',
    projectId: 'madic-834c8',
    storageBucket: 'madic-834c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMT4Z-n3V9tejIVCfmE1h1ck77uFKdRF8',
    appId: '1:396867608722:ios:13a3f5bdcf93888d7b064b',
    messagingSenderId: '396867608722',
    projectId: 'madic-834c8',
    storageBucket: 'madic-834c8.firebasestorage.app',
    iosClientId: '396867608722-hldjhovpb3upr7a99vq4noflt0i7g4fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.madic',
  );
}
